sudo: required
language: node_js
node_js:
  - 8
addons:
  chrome: stable
  sonarcloud:
    organization: at-08
    token:
      secure: "$SONAR_TOKEN"
before_install:
  - openssl aes-256-cbc -K $encrypted_4e0877d9a5af_key -iv $encrypted_4e0877d9a5af_iv
    -in environment.json.enc -out environment.json -d
  - google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 http://localhost &
script:
  - npm install
  - sonar-scanner
  - npm run lint
  - npm run travis
notifications:
  email: true
